# version: 0.2

#   build:
#     commands:
#       - cmake -S. -B build -D CMAKE_BUILD_TYPE=Release -D BUILD_TESTS=ON -D UPDATE_DEPS=ON -D LOADER_ENABLE_ADDRESS_SANITIZER=ON -D BUILD_WERROR=ON -D CMAKE_CXX_COMPILER=clang++ -D CMAKE_C_COMPILER=clang
#       - cmake --build build
#       - ctest --output-on-failure --test-dir build/
#       - cmake --install build --prefix /tmp
# artifacts:
#   files:
#     - '**/*'
#   name: vulkan-loader-build-output-$(date +%Y-%m-%d)
#   base-directory: '/tmp/lib' # Adjust this based on where your artifacts are generated
#   discard-paths: yes
#   s3:
#     bucket: khr-github-build-artifacts
#     path: today/