steps:
  # Build configuration
  - name: 'us-west2-docker.pkg.dev/github-test-builds-419921/ooctest/vulkan-loader-image:latest'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - | 
        cmake -S. -B build \
        -D CMAKE_BUILD_TYPE=Debug \
        -D BUILD_TESTS=ON \
        -D UPDATE_DEPS=ON \
        -D LOADER_ENABLE_ADDRESS_SANITIZER=ON \
        -D BUILD_WERROR=ON \
        -D CMAKE_CXX_COMPILER=g++ \
        -D CMAKE_C_COMPILER=gcc && \
        cmake --build build
  - name: 'us-west2-docker.pkg.dev/github-test-builds-419921/ooctest/vulkan-loader-image:latest'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        ctest --output-on-failure --test-dir build/

  - name: 'us-west2-docker.pkg.dev/github-test-builds-419921/ooctest/vulkan-loader-image:latest'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        cmake --install build --prefix /tmp

  - name: 'us-west2-docker.pkg.dev/github-test-builds-419921/ooctest/vulkan-loader-image:latest'
    args: ['-m', 'cp', '-r', '/tmp/lib', 'gs://test-ooc/${_ARTIFACT_NAME}/']
# This section is to specify artifacts to be stored
# artifacts:
#   objects:
#     location: 'gs://test-ooc/${_ARTIFACT_NAME}/'
#     paths:
#       - '/tmp/lib/**'
    
# Substitutions
options:
  automapSubstitutions: true
substitutions:
  _ARTIFACT_NAME: 'Vulkan-Loader-$SHORT_SHA'
