name: CI Build

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id  }}
  cancel-in-progress: true

on:
  push:
  pull_request:
    branches:
    - main

permissions: read-all

jobs:
    linux:
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                compiler: [ {cc: clang, cxx: clang++} ]
                config: [ Release ]
                os: [ ubuntu-20.04 ]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.7'
            - name: Test CMake min
              if: ${{ matrix.os == 'ubuntu-20.04' }}
              uses: lukka/get-cmake@latest
              with:
                cmakeVersion: 3.17.2
            - run: sudo apt update
            - run: sudo apt install --yes --no-install-recommends libwayland-dev libxrandr-dev
            - run: sudo sysctl vm.mmap_rnd_bits=28
            - run: |
                cmake -S. -B build \
                -D CMAKE_BUILD_TYPE=${{ matrix.config }} \
                -D BUILD_TESTS=ON \
                -D UPDATE_DEPS=ON \
                -D LOADER_ENABLE_ADDRESS_SANITIZER=ON \
                -D BUILD_WERROR=ON \
                -D CMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }} \
                -D CMAKE_C_COMPILER=${{ matrix.compiler.cc }}
            - run: cmake --build build
            - run: ctest --output-on-failure --test-dir build/
            - run: cmake --install build --prefix /tmp
